//! Windows install path for `parsec tray` — a `HKCU\...\Run` entry, no
//! bundle, no admin.
//!
//! Windows has no `.app` equivalent, and it needs none: the icon comes from
//! the running process (`app.rs` sets both the tray and the window icon from
//! the embedded brand PNG), and "start at login" is one registry value under
//! the CURRENT USER hive — matching what `setup_desktop` already does for the
//! interceptor, and keeping install.ps1's "no admin rights needed" promise.
//!
//! Two Windows-specific problems this file exists to solve:
//!
//! 1. **The console window.** `parsec.exe` is a console-subsystem binary (no
//!    `#![windows_subsystem]`, deliberately — every other subcommand writes
//!    to stdout and a GUI subsystem would silence them). Launching it for the
//!    tray therefore allocates a console. [`detach_console`] frees it at
//!    startup, and the Run entry goes through a hidden-window launcher so
//!    there is no flash at login either.
//! 2. **Taskbar presence.** Unlike the macOS Dock, a Windows taskbar button
//!    requires a visible top-level window — `app.rs` creates one for exactly
//!    that reason.

use std::path::PathBuf;
use std::process::Command;

use super::{target_binary, LABEL};

const RUN_KEY: &str = r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run";
const RUN_NAME: &str = "ParsecTray";

/// A `.vbs` shim, and the reason is narrow: `WScript.Shell.Run` with
/// `intWindowStyle = 0` starts a console binary with NO console window at
/// all. Putting `parsec.exe tray run` in the Run key directly would flash a
/// console at every login — `detach_console` closes it, but only after it has
/// already appeared.
fn launcher_path() -> PathBuf {
    crate::setup::parsec_home().join("parsec-tray.vbs")
}

fn launcher_script(binary: &std::path::Path) -> String {
    // VBScript escapes a double quote by doubling it.
    let exe = binary.display().to_string().replace('"', "\"\"");
    format!(
        "' parsec-managed — generated by `parsec tray install`.\r\n\
         ' Starts the tray with no console window (0 = hidden, False = don't wait).\r\n\
         CreateObject(\"WScript.Shell\").Run \"\"\"{exe}\"\" tray run\", 0, False\r\n"
    )
}

/// Detach from the console the loader handed us. Called once at tray startup.
///
/// Safety: `FreeConsole` takes no arguments, has no failure mode we act on,
/// and is safe to call when no console is attached (it just returns 0). This
/// is the whole unsafe surface of the Windows tray.
pub fn detach_console() {
    #[link(name = "kernel32")]
    extern "system" {
        fn FreeConsole() -> i32;
    }
    unsafe {
        FreeConsole();
    }
}

pub fn installed() -> bool {
    Command::new("reg")
        .args(["query", RUN_KEY, "/v", RUN_NAME])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

pub fn install() -> anyhow::Result<()> {
    let binary = target_binary();
    if !binary.exists() {
        anyhow::bail!(
            "no parsec binary at {} — run `parsec setup` first so the stable alias exists",
            binary.display()
        );
    }
    let launcher = launcher_path();
    if let Some(dir) = launcher.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&launcher, launcher_script(&binary))?;

    // wscript, not cscript: cscript is the console host and would defeat the
    // point. The path is quoted because %USERPROFILE% routinely has a space.
    let cmd = format!("wscript.exe \"{}\"", launcher.display());
    let ok = Command::new("reg")
        .args(["add", RUN_KEY, "/v", RUN_NAME, "/t", "REG_SZ", "/d"])
        .arg(&cmd)
        .arg("/f")
        .stdout(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        anyhow::bail!("could not write the {RUN_NAME} entry under {RUN_KEY}");
    }

    // Start it now so the icon appears without a logout/login round trip.
    let started = Command::new("wscript.exe").arg(&launcher).spawn().is_ok();

    println!(
        "{}",
        crate::brand::panel(
            "tray app",
            &[
                if started {
                    "started — the mark is in your notification area and taskbar"
                } else {
                    "registered — it starts at your next sign-in"
                },
                "~launcher: %USERPROFILE%\\\\.parsec\\\\parsec-tray.vbs",
                "~startup: HKCU\\\\...\\\\CurrentVersion\\\\Run → ParsecTray",
                "~listed in Task Manager → Startup apps",
                "~remove anytime: parsec tray uninstall",
            ],
        )
    );
    Ok(())
}

pub fn uninstall() -> anyhow::Result<()> {
    let had = installed();
    let _ = Command::new("reg")
        .args(["delete", RUN_KEY, "/v", RUN_NAME, "/f"])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();
    let _ = std::fs::remove_file(launcher_path());
    // A running tray keeps its icon until it exits; say so rather than
    // implying the icon vanishes.
    println!(
        "{}",
        if had {
            "tray app removed (a running one keeps its icon until you quit it)"
        } else {
            "tray app was not installed"
        }
    );
    Ok(())
}

pub fn status() -> anyhow::Result<()> {
    println!("TRAY APP");
    println!(
        "  installed:   {}",
        if installed() {
            "yes"
        } else {
            "no — install with: parsec tray install"
        }
    );
    println!("  launcher:    {}", launcher_path().display());
    println!("  startup:     {RUN_KEY} → {RUN_NAME}");
    println!("  runs:        {} tray run", target_binary().display());
    println!("  log:         {}", super::log_path().display());
    let _ = LABEL; // shared identity constant; unused on this platform
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launcher_hides_the_console_and_quotes_the_path() {
        let s = launcher_script(std::path::Path::new(
            r"C:\Users\First Last\.parsec\bin\parsec.exe",
        ));
        // 0 = hidden window: the whole reason the .vbs exists.
        assert!(s.contains("\", 0, False"));
        // A space in the profile path must not split the command.
        assert!(s.contains(r#"""C:\Users\First Last\.parsec\bin\parsec.exe"" tray run"#));
        assert!(s.contains("parsec-managed"));
        // CRLF: Windows Script Host is happier, and it is a Windows file.
        assert!(s.contains("\r\n"));
    }

    #[test]
    fn a_quote_in_the_path_cannot_break_out_of_the_vbs_string() {
        let s = launcher_script(std::path::Path::new(r#"C:\a"b\parsec.exe"#));
        // VBScript escapes a quote by doubling it; the injected one must be
        // doubled on top of the surrounding pair.
        assert!(s.contains(r#"C:\a""b\parsec.exe"#));
    }
}
