//! Hash-embedder parity (§7b): replays fixtures generated by
//! parity/gen_embed_fixtures.py from the vendored Python `_hash_embed` and
//! asserts BIT equality with engine::embed::hash_embed — same battery, same
//! dims, u32 bit patterns of the float32 narrowing. Regenerate with:
//!   packages/brain/.venv/bin/python parity/gen_embed_fixtures.py

use dasein_engine::embed::hash_embed;
use serde_json::Value;

#[test]
fn hash_embed_bit_parity() {
    let path = format!(
        "{}/parity/fixtures/hash_embed.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!("missing {path} — run: packages/brain/.venv/bin/python parity/gen_embed_fixtures.py")
    });
    let fx: Value = serde_json::from_str(&data).expect("fixture parse");
    let cases = fx["cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let text = case["text"].as_str().unwrap();
        let dim = case["dim"].as_u64().unwrap() as usize;
        let want: Vec<u32> = case["bits"]
            .as_array()
            .unwrap()
            .iter()
            .map(|b| b.as_u64().unwrap() as u32)
            .collect();
        let got: Vec<u32> = hash_embed(text, dim).iter().map(|f| f.to_bits()).collect();
        let label: String = text.chars().take(40).collect();
        assert_eq!(got, want, "bit mismatch for text={label:?} dim={dim}");
    }
}
