//! det NEEDED-LABEL parity suite: replays sessions generated by
//! parity/gen_needed.py through engine::needed::det_trim and asserts the
//! chunk set, the keep indices, and the rendered body EXACTLY against the
//! Python reference (the dasein-trim deps snapshot — the code the SWE-bench
//! det arm measured). Regenerate fixtures with:
//!   ../brain/.venv/bin/python parity/gen_needed.py

use parsec_engine::needed::{det_trim, TrimSkip};
use serde_json::Value;

fn load() -> Vec<Value> {
    let path = format!("{}/parity/fixtures/needed.json", env!("CARGO_MANIFEST_DIR"));
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "missing needed parity fixtures — run: ../brain/.venv/bin/python parity/gen_needed.py"
        )
    });
    serde_json::from_str(&data).expect("fixture parse")
}

fn as_i64(v: &Value) -> Option<i64> {
    v.as_i64()
}

#[test]
fn parity_det_keep_set() {
    for case in load() {
        let name = case["name"].as_str().unwrap();
        let messages: Vec<Value> = case["messages"].as_array().unwrap().clone();
        let patch = case["patch"].as_str().unwrap();
        let expected = &case["expected"];

        if let Some(skip) = expected.get("skip").and_then(Value::as_str) {
            let err = det_trim(&messages, patch).expect_err(name);
            let n = expected["n"].as_u64().unwrap() as usize;
            match (skip, &err) {
                ("steps", TrimSkip::TooFewSteps(g)) => assert_eq!(*g, n, "{name}: skip count"),
                ("chunks", TrimSkip::TooFewChunks(g)) => assert_eq!(*g, n, "{name}: skip count"),
                other => panic!("{name}: unexpected skip pairing {other:?}"),
            }
            continue;
        }

        let d = det_trim(&messages, patch).unwrap_or_else(|e| panic!("{name}: {e}"));

        // chunk-for-chunk: text, file, lo, hi, step, kind, tokens
        let exp_chunks = expected["chunks"].as_array().unwrap();
        assert_eq!(d.chunks.len(), exp_chunks.len(), "{name}: chunk count");
        for (i, (got, exp)) in d.chunks.iter().zip(exp_chunks).enumerate() {
            assert_eq!(got.text, exp["text"].as_str().unwrap(), "{name}[{i}].text");
            assert_eq!(
                got.file.as_deref(),
                exp["file"].as_str(),
                "{name}[{i}].file"
            );
            assert_eq!(got.lo, as_i64(&exp["lo"]), "{name}[{i}].lo");
            assert_eq!(got.hi, as_i64(&exp["hi"]), "{name}[{i}].hi");
            assert_eq!(got.step, exp["step"].as_i64().unwrap(), "{name}[{i}].step");
            assert_eq!(got.kind, exp["kind"].as_str().unwrap(), "{name}[{i}].kind");
            assert_eq!(
                got.tokens,
                exp["tokens"].as_i64().unwrap(),
                "{name}[{i}].tokens"
            );
        }

        // the det keep-set, index-for-index
        let got_keep: Vec<usize> = d
            .keep
            .iter()
            .enumerate()
            .filter(|(_, &k)| k)
            .map(|(i, _)| i)
            .collect();
        let exp_keep: Vec<usize> = expected["keep_idx"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        assert_eq!(got_keep, exp_keep, "{name}: keep indices");

        // reasoning chunks must never enter the keep-set
        for &i in &got_keep {
            assert_ne!(d.chunks[i].kind, "reasoning", "{name}: reasoning kept");
        }

        // rendered body, byte-for-byte
        assert_eq!(
            d.render(),
            expected["rendered"].as_str().unwrap(),
            "{name}: rendered body"
        );
    }
}
