//! Cross-language parity suite (DIRECTION.md §7b, §8): replays fixtures
//! generated by parity/gen_fixtures.py against the Python reference and
//! asserts exact equality — chunk-for-chunk on chunking, value-for-value on
//! features. Regenerate fixtures with:
//!   python3 parity/gen_fixtures.py fixed && python3 parity/gen_fixtures.py cst

use parsec_engine::chunking::{
    accumulated_chunks, chunk_assistant, chunk_observation, Chunk, ChunkMode, DEFAULT_WIN,
};
use parsec_engine::features::dup_feats_fast;
use parsec_engine::messages;
use serde_json::Value;

fn load(mode: &str) -> Option<Value> {
    let path = format!(
        "{}/parity/fixtures/chunking_{}.json",
        env!("CARGO_MANIFEST_DIR"),
        mode
    );
    let data = std::fs::read_to_string(&path).ok()?;
    Some(serde_json::from_str(&data).expect("fixture parse"))
}

fn chunks_value(chunks: &[Chunk]) -> Value {
    serde_json::to_value(chunks).unwrap()
}

fn steps_from(v: &Value) -> Vec<(String, String)> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|s| {
            let a = s.as_array().unwrap();
            (
                a[0].as_str().unwrap().to_string(),
                a[1].as_str().unwrap().to_string(),
            )
        })
        .collect()
}

fn run_mode(mode_name: &str, mode: ChunkMode) {
    let Some(fx) = load(mode_name) else {
        panic!(
            "missing parity fixtures for mode '{mode_name}' — run: python3 parity/gen_fixtures.py {mode_name}"
        );
    };

    for case in fx["chunk_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let read_lines = case["read_lines"].as_u64().map(|g| g as usize);
        let got = chunk_observation(
            case["cmd"].as_str().unwrap(),
            case["obs"].as_str().unwrap(),
            case["step"].as_i64().unwrap(),
            DEFAULT_WIN,
            read_lines,
            mode,
        );
        assert_eq!(
            chunks_value(&got),
            case["expected"],
            "chunk case '{name}' ({mode_name})"
        );
    }

    for case in fx["assistant_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let got = chunk_assistant(
            case["txt"].as_str().unwrap(),
            case["step"].as_i64().unwrap(),
            DEFAULT_WIN,
        );
        assert_eq!(
            chunks_value(&got),
            case["expected"],
            "assistant case '{name}'"
        );
    }

    for case in fx["accum_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let steps = steps_from(&case["steps"]);
        let read_lines = case["read_lines"].as_u64().map(|g| g as usize);
        let got = accumulated_chunks(
            &steps,
            case["upto"].as_u64().unwrap() as usize,
            read_lines,
            mode,
        );
        assert_eq!(
            chunks_value(&got),
            case["expected"],
            "accum case '{name}' ({mode_name})"
        );
    }

    for case in fx["dup_cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let steps = steps_from(&case["steps"]);
        let read_lines = case["read_lines"].as_u64().map(|g| g as usize);
        let chunks = accumulated_chunks(
            &steps,
            case["upto"].as_u64().unwrap() as usize,
            read_lines,
            mode,
        );
        let (sup, dup) = dup_feats_fast(&chunks, None);
        assert_eq!(
            serde_json::to_value(&sup).unwrap(),
            case["expected_sup"],
            "dup sup '{name}'"
        );
        assert_eq!(
            serde_json::to_value(&dup).unwrap(),
            case["expected_dup_earlier"],
            "dup earlier '{name}'"
        );
        let rows: Vec<usize> = case["rows"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        let (sup_r, dup_r) = dup_feats_fast(&chunks, Some(&rows));
        assert_eq!(
            serde_json::to_value(&sup_r).unwrap(),
            case["expected_sup_rows"],
            "dup sup rows '{name}'"
        );
        assert_eq!(
            serde_json::to_value(&dup_r).unwrap(),
            case["expected_dup_earlier_rows"],
            "dup earlier rows '{name}'"
        );
    }

    let mc = &fx["message_case"];
    let msgs: Vec<Value> = mc["messages"].as_array().unwrap().clone();
    let steps = messages::steps_of(&msgs);
    let steps_v: Value = serde_json::to_value(
        steps
            .iter()
            .map(|(a, b)| vec![a.clone(), b.clone()])
            .collect::<Vec<_>>(),
    )
    .unwrap();
    assert_eq!(steps_v, mc["expected_steps"], "steps_of");
    assert_eq!(
        chunks_value(&messages::reasoning_chunks_of(&msgs)),
        mc["expected_reasoning"],
        "reasoning_chunks_of"
    );
    assert_eq!(
        chunks_value(&messages::assistant_chunks_of(&msgs)),
        mc["expected_assistant"],
        "assistant_chunks_of"
    );
    let blobs: Vec<i64> = msgs.iter().map(messages::blob_tokens).collect();
    assert_eq!(
        serde_json::to_value(&blobs).unwrap(),
        mc["expected_blob_tokens"],
        "blob_tokens"
    );
}

#[test]
fn parity_fixed_mode() {
    run_mode("fixed", ChunkMode::Fixed);
}

#[test]
fn parity_cst_mode() {
    run_mode("cst", ChunkMode::Cst);
}
