//! RE-REQUEST column parity: replays the chunk sets generated by
//! parity/gen_rereq_fixtures.py (gnn-train torch_curator at the HS revision)
//! through `rereq::rereq_columns` and asserts f32 BIT-equality, plus the
//! most-recent-copy index and the r3 bash-read / path-normalisation helpers.
//! Regenerate with:
//!   GNN_TRAIN=<gnn-train checkout> <venv>/bin/python parity/gen_rereq_fixtures.py

use std::collections::HashSet;

use parsec_engine::chunking::Chunk;
use parsec_engine::rereq::{bash_read_targets, ft_norm, rereq_base, rereq_columns};
use parsec_engine::v3::ext_class;
use serde_json::Value;

fn load() -> Value {
    let path = format!("{}/parity/fixtures/rereq.json", env!("CARGO_MANIFEST_DIR"));
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!("missing rereq parity fixtures — run parity/gen_rereq_fixtures.py")
    });
    serde_json::from_str(&data).expect("fixture parse")
}

#[test]
fn parity_rereq_columns() {
    let fx = load();
    let cases = fx["cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let chunks: Vec<Chunk> = serde_json::from_value(case["chunks"].clone()).unwrap();
        let cut: HashSet<usize> = case["cut"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();

        let (_, mr) = rereq_base(&chunks);
        let want_mr: Vec<Option<usize>> = case["mr_idx"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| usize::try_from(v.as_i64().unwrap()).ok())
            .collect();
        assert_eq!(mr, want_mr, "{name}: most-recent-copy index");

        let got = rereq_columns(&chunks, |j| cut.contains(&j));
        let want = case["rereq"].as_array().unwrap();
        assert_eq!(got.len(), want.len(), "{name}: row count");
        for (i, (g, w)) in got.iter().zip(want).enumerate() {
            for (k, wv) in w.as_array().unwrap().iter().enumerate() {
                let wf = wv.as_f64().unwrap() as f32;
                let gf = g[k] as f32;
                assert_eq!(
                    gf.to_bits(),
                    wf.to_bits(),
                    "{name}: row {i} col {k}: got {gf} want {wf}"
                );
            }
        }
    }
}

#[test]
fn parity_bash_read_targets() {
    let fx = load();
    for case in fx["bash"].as_array().unwrap() {
        let cmd = case["cmd"].as_str().unwrap();
        let want: Vec<(String, i64, i64)> = case["targets"]
            .as_array()
            .unwrap()
            .iter()
            .map(|t| {
                let t = t.as_array().unwrap();
                (
                    t[0].as_str().unwrap().to_string(),
                    t[1].as_i64().unwrap(),
                    t[2].as_i64().unwrap(),
                )
            })
            .collect();
        assert_eq!(bash_read_targets(cmd), want, "cmd {cmd:?}");
    }
}

#[test]
fn parity_ft_norm() {
    let fx = load();
    for case in fx["norm"].as_array().unwrap() {
        let input = case["in"].as_str().unwrap();
        assert_eq!(
            ft_norm(input),
            case["out"].as_str().unwrap(),
            "in {input:?}"
        );
    }
}

#[test]
fn parity_ext_class() {
    let fx = load();
    for case in fx["ext_class"].as_array().unwrap() {
        let file = case["file"].as_str();
        assert_eq!(
            ext_class(file),
            case["class"].as_str().unwrap(),
            "file {file:?}"
        );
    }
}
