//! NODE-featurization parity suite (DIRECTION.md §7b): replays chunk sets
//! generated by parity/gen_feature_fixtures.py through the Rust port of
//! torch_curator's feature stack and asserts f32 BIT-equality against the
//! Python reference (which emits float32; we compute f64 and downcast once —
//! the same single rounding). Regenerate fixtures with:
//!   ../brain/.venv/bin/python parity/gen_feature_fixtures.py

use parsec_engine::chunking::Chunk;
use parsec_engine::features::{
    markers, node_struct_with_type, spans, struct_features, struct_features_causal,
    struct_type_features, supersession_edges,
};
use serde_json::Value;

fn load() -> Value {
    let path = format!(
        "{}/parity/fixtures/features.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "missing feature parity fixtures — run: ../brain/.venv/bin/python parity/gen_feature_fixtures.py"
        )
    });
    serde_json::from_str(&data).expect("fixture parse")
}

/// rel-4 supersession pairs vs the VENDORED pyg_model.edges emission (et==4
/// filtered), pair-for-pair INCLUDING order (the brain's v1 path re-sorts the
/// client pairs into exactly the vendored loop order — set equality would
/// hide an ordering bug in this port's loop structure).
#[test]
fn parity_supersession_edges() {
    let path = format!(
        "{}/parity/fixtures/supersession.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let data = std::fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "missing supersession parity fixtures — run: ../brain/.venv/bin/python parity/gen_supersession_fixtures.py"
        )
    });
    let fx: Value = serde_json::from_str(&data).expect("fixture parse");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let chunks: Vec<Chunk> = serde_json::from_value(case["chunks"].clone()).unwrap();
        let got: Vec<Vec<usize>> = supersession_edges(&chunks)
            .into_iter()
            .map(|(a, b)| vec![a, b])
            .collect();
        let want: Vec<Vec<usize>> = serde_json::from_value(case["expected"].clone()).unwrap();
        assert_eq!(
            got, want,
            "{name}: rel-4 pairs diverged from vendored edges()"
        );
    }
}

/// f32 bit-equality between the Rust f64 matrix (downcast once) and the
/// fixture's float32 values (exact in the JSON f64s).
fn assert_mat<const N: usize>(got: &[[f64; N]], want: &Value, ctx: &str) {
    let rows = want.as_array().unwrap();
    assert_eq!(got.len(), rows.len(), "{ctx}: row count");
    for (r, (g, w)) in got.iter().zip(rows).enumerate() {
        let w = w.as_array().unwrap();
        assert_eq!(w.len(), N, "{ctx}: width at row {r}");
        for (k, (gv, wv)) in g.iter().zip(w).enumerate() {
            let want32 = wv.as_f64().unwrap() as f32;
            let got32 = *gv as f32;
            assert_eq!(
                got32.to_bits(),
                want32.to_bits(),
                "{ctx}: row {r} col {k}: got {got32:e} want {want32:e}"
            );
        }
    }
}

#[test]
fn parity_spans() {
    let fx = load();
    for case in fx["span_cases"].as_array().unwrap() {
        let text = case["text"].as_str().unwrap();
        let mut got: Vec<String> = spans(text).into_iter().collect();
        got.sort();
        let want: Vec<&str> = case["expected"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        assert_eq!(got, want, "spans({text:?})");
    }
}

#[test]
fn parity_node_features() {
    let fx = load();
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let chunks: Vec<Chunk> = serde_json::from_value(case["chunks"].clone()).unwrap();
        let recent = case["recent"].as_str().unwrap();

        assert_mat(
            &struct_features(&chunks, recent, None),
            &case["struct_features"],
            &format!("{name}: struct_features"),
        );
        assert_mat(
            &struct_features_causal(&chunks),
            &case["causal"],
            &format!("{name}: struct_features_causal"),
        );
        assert_mat(
            &struct_type_features(&chunks, None),
            &case["type"],
            &format!("{name}: struct_type_features"),
        );
        assert_mat(
            &node_struct_with_type(&chunks),
            &case["node_struct"],
            &format!("{name}: node_struct_with_type"),
        );
        assert_mat(
            &markers(&chunks),
            &case["markers"],
            &format!("{name}: markers"),
        );

        if let Some(rows) = case["rows"].as_array() {
            let rows: Vec<usize> = rows.iter().map(|v| v.as_u64().unwrap() as usize).collect();
            assert_mat(
                &struct_features(&chunks, recent, Some(&rows)),
                &case["struct_features_rows"],
                &format!("{name}: struct_features rows"),
            );
            assert_mat(
                &struct_type_features(&chunks, Some(&rows)),
                &case["type_rows"],
                &format!("{name}: struct_type_features rows"),
            );
        }
    }
}
