"""Generate theme.css from tokens.json. Run from any working directory."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

HELPERS = """
/* Optional, scoped UI helpers. Load Roboto Serif 400 and Inter 300/500 in the app. */
.parsec-root {
  background: var(--parsec-bg);
  color: var(--parsec-text);
  font-family: var(--parsec-font-sans);
  font-size: var(--parsec-fs-base);
  font-weight: var(--parsec-fw-light);
  line-height: var(--parsec-lh-normal);
  letter-spacing: var(--parsec-ls-body);
}
.parsec-title {
  font-family: var(--parsec-font-display);
  font-weight: var(--parsec-fw-regular);
  line-height: var(--parsec-lh-tight);
  letter-spacing: var(--parsec-ls-display);
}
.parsec-subheading {
  font-family: var(--parsec-font-sans);
  font-weight: var(--parsec-fw-medium);
  font-size: var(--parsec-fs-sm);
  line-height: var(--parsec-lh-snug);
  letter-spacing: var(--parsec-ls-caps);
  text-transform: uppercase;
}
.parsec-code { font-family: var(--parsec-font-mono); font-weight: var(--parsec-fw-regular); }
/* Emphasized text stays monochrome. Use green only as a fill or graphic. */
.parsec-accent { color: var(--parsec-text); font-weight: var(--parsec-fw-medium); }
.parsec-highlight { background: var(--parsec-primary); color: var(--parsec-on-primary); }
.parsec-link { color: var(--parsec-link); text-decoration: underline; text-underline-offset: 0.2em; }
.parsec-btn {
  font-family: var(--parsec-font-sans);
  font-size: var(--parsec-fs-sm);
  font-weight: var(--parsec-fw-medium);
  background: var(--parsec-primary);
  color: var(--parsec-on-primary);
  border: var(--parsec-bw-hairline) solid transparent;
  border-radius: var(--parsec-radius-pill);
  padding: var(--parsec-space-3) var(--parsec-space-5);
  cursor: pointer;
  transition: border-color var(--parsec-motion-fast) var(--parsec-ease);
}
.parsec-btn:hover { border-color: var(--parsec-border-strong); }
.parsec-btn:active { outline: var(--parsec-bw-hairline) solid var(--parsec-focus); outline-offset: 2px; }
.parsec-btn--ghost {
  background: transparent;
  color: var(--parsec-text);
  border-color: var(--parsec-border);
}
.parsec-btn:disabled { cursor: not-allowed; opacity: 0.5; }
.parsec-card {
  background: var(--parsec-surface);
  border: var(--parsec-bw-hairline) solid var(--parsec-border);
  border-radius: var(--parsec-radius-lg);
  box-shadow: var(--parsec-shadow-none);
}
.parsec-root :focus-visible, .parsec-btn:focus-visible, .parsec-link:focus-visible {
  outline: var(--parsec-bw-focus) solid var(--parsec-focus);
  outline-offset: 4px;
}
.parsec-root ::selection { background: var(--parsec-selection); color: var(--parsec-on-selection); }
@media (prefers-reduced-motion: reduce) {
  .parsec-btn { transition: none; }
}
"""


def generate():
    tokens = json.loads((HERE / "tokens.json").read_text())
    themes = tokens["color"]["themes"]
    lines = [
        "/* Generated by gen_theme.py from tokens.json; edit the source and regenerate.",
        "   Black/white first; green fills only. Dark by default, light by explicit choice. */",
        "", ":root {", "  color-scheme: dark;",
    ]

    def emit(name, value):
        lines.append(f"  --parsec-{name}: {value};")

    for name, token in tokens["color"]["brand"].items():
        emit(name, token["value"])
    for name, token in themes["dark"].items():
        emit(name, token["value"])
    for name in ("display", "sans", "mono"):
        emit(f"font-{name}", tokens["font"][name]["value"])
    for name, value in tokens["font"]["weight"].items():
        emit(f"fw-{name}", value)
    for name, token in tokens["fontSize"].items():
        emit(f"fs-{name}", token["value"])
    for group, prefix in [("lineHeight", "lh"), ("letterSpacing", "ls"),
                          ("space", "space"), ("radius", "radius"), ("border", "bw")]:
        for name, value in tokens[group].items():
            emit(f"{prefix}-{name}", value)
    emit("shadow-none", tokens["shadow"]["none"]["value"])
    for name, value in tokens["motion"].items():
        emit("ease" if name == "ease" else f"motion-{name}", value)
    lines.extend(["}", "", ':root[data-theme="light"] {', "  color-scheme: light;"])
    for name, token in themes["light"].items():
        emit(name, token["value"])
    lines.append("}")
    (HERE / "theme.css").write_text("\n".join(lines) + "\n" + HELPERS)


if __name__ == "__main__":
    generate()
    print("Generated tokens/theme.css")
