//! §8.1 recorded-conversation golden test (DIRECTION.md invariant 1): replay
//! a real (sanitized) multi-turn Claude Code conversation through the actual
//! proxy — mock brain + mock upstream — and assert the cache law held:
//! every previously-served turn byte-identical, simulated cache_read /
//! cache_write ≥ 10:1, the brain consulted, content actually trimmed, and no
//! request-level fail-open. The fixture is generated by
//! scripts/record_to_fixture.py (structure real, content scrambled);
//! scripts/golden_replay.sh runs the same replay against the REAL brain.

use std::collections::HashSet;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use axum::body::{Body, Bytes};
use axum::extract::State;
use axum::http::{header, HeaderMap, StatusCode};
use axum::response::Response;
use axum::routing::post;
use axum::Router;
use serde_json::{json, Value};

use dasein_engine::pystr::{char_len, py_json_dumps};
use dasein_proxy::brain::BrainConfig;
use dasein_proxy::server::{router, AppState};
use dasein_proxy::splice::strip_cache_control;

/// Grid tau the mock brain hands out (the real ckpt's 0.70-cov tau).
const TAU_Q: i64 = 315_265;

// ── mock upstream (canned Anthropic) ────────────────────────────────────────

#[derive(Clone, Default)]
struct Upstream {
    reqs: Arc<Mutex<Vec<Value>>>,
}

async fn upstream_messages(State(u): State<Upstream>, _h: HeaderMap, raw: Bytes) -> Response {
    u.reqs
        .lock()
        .unwrap()
        .push(serde_json::from_slice(&raw).unwrap_or(Value::Null));
    let msg = json!({
        "id": "msg_mock", "type": "message", "role": "assistant",
        "content": [{"type": "text", "text": "ok"}],
        "stop_reason": "end_turn",
        "usage": {"input_tokens": 100, "output_tokens": 5,
                  "cache_creation_input_tokens": 7, "cache_read_input_tokens": 50}
    });
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(msg.to_string()))
        .unwrap()
}

async fn upstream_count(_h: HeaderMap, _raw: Bytes) -> Response {
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(json!({"input_tokens": 1234}).to_string()))
        .unwrap()
}

// ── mock brain (tolerant: ANY live_gi/mask shape gets a valid response) ─────

#[derive(Clone, Default)]
struct MockBrain {
    trace_reqs: Arc<Mutex<usize>>,
    tools_reqs: Arc<Mutex<usize>>,
}

/// Mask rows score LOW (cut), everything else 1.0 — the freezer's own
/// budget-cut machinery decides what actually drops (proxy_brain.rs shape).
async fn brain_trace(State(b): State<MockBrain>, raw: Bytes) -> Response {
    *b.trace_reqs.lock().unwrap() += 1;
    let req: Value = serde_json::from_slice(&raw).unwrap_or(Value::Null);
    let n_live = req["live_gi"].as_array().map(Vec::len).unwrap_or(0);
    let mask: HashSet<u64> = req["mask"]
        .as_array()
        .map(|a| a.iter().filter_map(Value::as_u64).collect())
        .unwrap_or_default();
    let scores: Vec<i64> = (0..n_live as u64)
        .map(|j| {
            if mask.contains(&j) {
                100_000
            } else {
                1_000_000
            }
        })
        .collect();
    let resp = json!({
        "scores_q": scores, "tau_q": TAU_Q,
        "checkpoint_id": "c".repeat(64),
        "timings_ms": {"embed": 1.0, "forward": 1.0}
    });
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(resp.to_string()))
        .unwrap()
}

/// Tool head: every name scores identically — prune still cuts to the 0.70
/// mass target (tie-break by original index), the keep-set freezes once, and
/// the golden assertions don't depend on WHICH tools survive.
async fn brain_tools(State(b): State<MockBrain>, raw: Bytes) -> Response {
    *b.tools_reqs.lock().unwrap() += 1;
    let req: Value = serde_json::from_slice(&raw).unwrap_or(Value::Null);
    let names: Vec<String> = req["tools"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|t| t.get("name").and_then(Value::as_str))
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default();
    let scores: Vec<i64> = names.iter().map(|_| 990_000).collect();
    let tokens: Vec<i64> = names.iter().map(|_| 100).collect();
    let resp = json!({
        "names": names, "scores_q": scores, "tokens": tokens,
        "checkpoint_id": "c".repeat(64)
    });
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(resp.to_string()))
        .unwrap()
}

// ── harness (proxy_brain.rs pattern) ────────────────────────────────────────

struct Ctx {
    url: String,
    upstream: Upstream,
    brain: MockBrain,
    ledger: PathBuf,
    http: reqwest::Client,
}

async fn setup() -> Ctx {
    static SEQ: AtomicU64 = AtomicU64::new(0);
    let upstream = Upstream::default();
    let up_router = Router::new()
        .route("/v1/messages", post(upstream_messages))
        .route("/v1/messages/count_tokens", post(upstream_count))
        .with_state(upstream.clone());
    let ul = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let up_addr = ul.local_addr().unwrap();
    tokio::spawn(async move { axum::serve(ul, up_router).await.unwrap() });

    let brain = MockBrain::default();
    let brain_router = Router::new()
        .route("/v1/score/trace", post(brain_trace))
        .route("/v1/score/tools", post(brain_tools))
        .with_state(brain.clone());
    let bl = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let brain_addr = bl.local_addr().unwrap();
    tokio::spawn(async move { axum::serve(bl, brain_router).await.unwrap() });

    let ledger = std::env::temp_dir().join(format!(
        "dasein-golden-test-{}-{}.jsonl",
        std::process::id(),
        SEQ.fetch_add(1, Ordering::Relaxed)
    ));
    let _ = std::fs::remove_file(&ledger);
    let cfg = BrainConfig {
        url: format!("http://{brain_addr}"),
        key: None,
        timeout: Duration::from_secs(30),
        target_cov: "0.70".into(),
        tool_cut: 0.70,
        tool_prune: true,
        contract: dasein_proxy::brain::BrainContract::Dev,
        embed_backend: "hash".into(),
        embed_url: None,
        onnx_dir: None,
    };
    let state = Arc::new(AppState::with_brain(
        format!("http://{up_addr}"),
        ledger.clone(),
        Some(cfg),
    ));
    let pl = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let proxy_addr = pl.local_addr().unwrap();
    let app = router(state);
    tokio::spawn(async move { axum::serve(pl, app).await.unwrap() });

    Ctx {
        url: format!("http://{proxy_addr}"),
        upstream,
        brain,
        ledger,
        http: reqwest::Client::new(),
    }
}

fn fixture_turns() -> Vec<Value> {
    let p =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("parity/fixtures/golden_conversation.json");
    let raw = std::fs::read(&p).unwrap_or_else(|e| panic!("golden fixture {p:?}: {e}"));
    let v: Value = serde_json::from_slice(&raw).expect("fixture parses");
    v["turns"].as_array().expect("fixture .turns").clone()
}

fn ledger_rows(ctx: &Ctx) -> Vec<Value> {
    std::fs::read_to_string(&ctx.ledger)
        .map(|s| {
            s.lines()
                .filter(|l| !l.trim().is_empty())
                .map(|l| serde_json::from_str(l).unwrap())
                .collect()
        })
        .unwrap_or_default()
}

/// chars/4 over CPython-parity JSON bytes — the same token proxy the
/// engine's internal mass diagnostics use.
fn tok(msgs: &[Value]) -> i64 {
    char_len(&py_json_dumps(&Value::Array(msgs.to_vec()))) as i64 / 4
}

// ── the test ────────────────────────────────────────────────────────────────

#[tokio::test(flavor = "multi_thread")]
async fn golden_conversation_replay() {
    let ctx = setup().await;
    let turns = fixture_turns();
    assert!(
        turns.len() >= 15,
        "fixture too short: {} turns",
        turns.len()
    );

    // The record seam (§8.1 capture) is exercised by the same replay: with
    // DASEIN_RECORD_DIR set, every inbound body must be dumped verbatim.
    // This is the only test in this binary, so the process env is ours.
    let rec_dir = std::env::temp_dir().join(format!("dasein-golden-rec-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&rec_dir);
    std::env::set_var("DASEIN_RECORD_DIR", &rec_dir);

    for (k, b) in turns.iter().enumerate() {
        let resp = ctx
            .http
            .post(format!("{}/v1/messages", ctx.url))
            .header("x-api-key", "k")
            .json(b)
            .send()
            .await
            .unwrap();
        assert_eq!(resp.status(), 200, "turn {} not served", k + 1);
    }
    std::env::remove_var("DASEIN_RECORD_DIR");

    let sent = ctx.upstream.reqs.lock().unwrap().clone();
    assert_eq!(sent.len(), turns.len(), "not every turn reached upstream");

    // (a) BYTE STABILITY — the cache law: for every turn k, every message
    // the previous call served is byte-identical (anchors move; bytes don't).
    for k in 1..sent.len() {
        let prev = sent[k - 1]["messages"].as_array().unwrap();
        let cur = sent[k]["messages"].as_array().unwrap();
        assert!(prev.len() <= cur.len(), "turn {k} lost messages");
        for j in 0..prev.len() {
            assert_eq!(
                strip_cache_control(&prev[j]),
                strip_cache_control(&cur[j]),
                "turn {} message {j} changed bytes vs turn {k}",
                k + 1,
            );
        }
    }

    // (b) SIMULATED CACHE RATIO — frozen-prefix vs new-suffix token mass,
    // anchored at the deepest message proven byte-identical to the prior
    // call. Turn 1 is all cache write. §8.1: aggregate ≥ 10:1.
    let mut frozen_tot = 0i64;
    let mut new_tot = 0i64;
    let mut prev: Vec<Value> = Vec::new();
    println!("turn  msgs  frozen_tok  new_tok");
    for (k, s) in sent.iter().enumerate() {
        let msgs: Vec<Value> = s["messages"]
            .as_array()
            .unwrap()
            .iter()
            .map(strip_cache_control)
            .collect();
        let mut anchor = 0;
        while anchor < msgs.len() && anchor < prev.len() && msgs[anchor] == prev[anchor] {
            anchor += 1;
        }
        let (frozen, new) = (tok(&msgs[..anchor]), tok(&msgs[anchor..]));
        println!("{:>4}  {:>4}  {frozen:>10}  {new:>7}", k + 1, msgs.len());
        frozen_tot += frozen;
        new_tot += new;
        prev = msgs;
    }
    let ratio = frozen_tot as f64 / new_tot.max(1) as f64;
    println!("aggregate frozen:new = {frozen_tot}:{new_tot} ≈ {ratio:.1}:1");
    assert!(ratio >= 10.0, "simulated cache ratio {ratio:.2}:1 < 10:1");

    // (c) the brain was consulted and the freezer actually trimmed content.
    assert!(
        *ctx.brain.trace_reqs.lock().unwrap() > 0,
        "brain never consulted"
    );
    assert_eq!(
        *ctx.brain.tools_reqs.lock().unwrap(),
        1,
        "tool keep-set not frozen once"
    );
    let rows = ledger_rows(&ctx);
    assert_eq!(rows.len(), turns.len());
    let cut: i64 = rows
        .iter()
        .filter_map(|r| r["freeze_cut_tokens"].as_i64())
        .sum();
    assert!(cut > 0, "no turn was trimmed");
    let trimmed = sent.iter().any(|s| {
        serde_json::to_string(&s["messages"])
            .unwrap()
            .contains(" omitted ...]")
    });
    assert!(trimmed, "no omission marker in any served turn");

    // (d) no request-level fail-open, no scorer fail-open, ledger complete.
    for (i, r) in rows.iter().enumerate() {
        assert_eq!(r["fail_open"], false, "row {i} fail-opened");
        assert!(
            r.get("scorer_fail_opens").is_none(),
            "row {i} scorer fail-open: {r}"
        );
    }
    // Turn 1 (a single user message) has no birth step to replay, so not
    // every row carries the capture seam — but the conversation must.
    assert!(
        rows.iter().any(|r| r["checkpoint_id"] == "c".repeat(64)),
        "no ledger row carries checkpoint_id"
    );

    // Record seam: one conversation dir, every body dumped verbatim in order.
    let conv_dirs: Vec<_> = std::fs::read_dir(&rec_dir)
        .expect("record dir written")
        .filter_map(Result::ok)
        .collect();
    assert_eq!(conv_dirs.len(), 1, "expected one recorded conversation");
    let cdir = conv_dirs[0].path();
    for (k, t) in turns.iter().enumerate() {
        let raw = std::fs::read(cdir.join(format!("turn_{}.json", k + 1)))
            .unwrap_or_else(|e| panic!("recorded turn_{}.json: {e}", k + 1));
        let rec: Value = serde_json::from_slice(&raw).unwrap();
        assert_eq!(&rec, t, "recorded turn {} differs from inbound body", k + 1);
    }
    let _ = std::fs::remove_dir_all(&rec_dir);
}
